apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: xtdb-statefulset
  namespace: {{ .Release.Namespace }}
  labels:
    app: xtdb-statefulset
spec:
  serviceName: xtdb-service
  replicas: {{ .Values.nodeCount }}
  selector:
    matchLabels:
      app: xtdb-statefulset
  template:
    metadata:
      labels:
        app: xtdb-statefulset
      annotations: 
        checksum/config: {{ .Values.xtdbConfig.nodeConfig | sha256sum }}
    spec:
      volumes: 
        - name: "tmp"
          emptyDir: {}
        - name: xtdb-yaml-config
          configMap:
            name: xtdb-yaml-config
        - name: "local-disk-cache"
          emptyDir:
            sizeLimit: {{ .Values.xtdbConfig.localDiskCache.sizeLimit }}
        - name: "local-disk-bp"
          persistentVolumeClaim:
            claimName: xtdb-buffer-pool-claim
      containers:
        - name: xtdb-container
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args: ['-f', '/var/lib/xtdb-config/xtdbconfig.yaml']
          volumeMounts:
            - name: "tmp"
              mountPath: "/tmp"
            - mountPath: /var/lib/xtdb-config/xtdbconfig.yaml
              name: xtdb-yaml-config
              subPath: xtdbconfig.yaml
            - name: local-disk-cache
              mountPath: "/var/lib/xtdb/buffers/"
            - name: local-disk-bp
              mountPath: "/var/lib/xtdb/bufferpool/"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: XTDB_NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            {{- range $key, $value := .Values.xtdbConfig.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
