providerConfig:
  # AWS/EKS specific configuration
  env:
    AWS_S3_BUCKET: "xtdb-bench-bucket"
  serviceAccountAnnotations:
    eks.amazonaws.com/role-arn: "<service_account_role_arn>"
  nodeSelector:
    node_pool: xtdbpool
  # We mount and use the below YAML for configuring the XTDB nodes and their modules.
  # The !Env values are set by Environment Variables
  # See the XTDB configuration documentation for options: https://docs.xtdb.com/ops/config.html
  nodeConfig: |-
    server:
      host: '*'
      port: 5432

    logClusters:
      kafkaCluster: !Kafka
        bootstrapServers: !Env KAFKA_BOOTSTRAP_SERVERS
        propertiesMap:
          max.request.size: 5242880

    databases:
      xtdb:
        log: !Kafka
          cluster: kafkaCluster
          topic: !Env XTDB_LOG_TOPIC

        storage: !Remote
          objectStore: !S3
            bucket: !Env AWS_S3_BUCKET
            prefix: "xtdb-object-store"

    diskCache:
      path: /var/lib/xtdb/buffers/disk-cache

    healthz:
      host: '*'
      port: 8080

  kafka:
    controller:
      nodeSelector:
        node_pool: xtdbpool
