{
 "title": "JVM Memory Investigation",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "xtdbnode", "label": "XTDB Node", "query": { "query": "label_values(node_id)" } }
  ]
 },
 "panels": [
  { "title": "CAdvisor Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "cAdvisor Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"xtdb-oom-test\"}",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "container_memory_working_set_bytes{name=\"xtdb-oom-test\"}",
     "legendFormat": "Working Set"
    },
    {
     "expr": "container_memory_rss{name=\"xtdb-oom-test\"}",
     "legendFormat": "Resident Set"
    },
    {
     "expr": "container_spec_memory_limit_bytes{name=\"xtdb-oom-test\"}",
     "legendFormat": "Memory Limit"
    }
   ]
  },
  {
   "title": "cAdvisor Container Memory Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_cache{name=\"xtdb-oom-test\"}",
     "legendFormat": "Container Memory Cache"
    }
   ]
  },
  { "title": "JVM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "JVM Total Used Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{node_id=\"$xtdbnode\"})",
     "legendFormat": "$xtdbnode - Total Used Bytes"
    }
   ]
  },
  {
   "title": "JVM Total Direct Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_direct_bytes{node_id=\"$xtdbnode\"}",
     "legendFormat": "$xtdbnode - Total Direct Bytes"
    }
   ]
  },
  {
   "title": "Netty Used Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_netty_bytes{node_id=\"$xtdbnode\"}",
     "legendFormat": "$xtdbnode - Netty Used Memory"
    }
   ]
  },
  {
   "title": "XTDB - Buffer Pool Allocated Memory",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "memory_cache_evictableBytes_bytes{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} evictable bytes"
    },
    {
     "expr": "memory_cache_freeBytes_bytes{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} free bytes"
    },
    {
     "expr": "memory_cache_pinnedBytes_bytes{node_id=\"$xtdbnode\"}",
     "legendFormat": "{{node_id}} pinned bytes"
    }
   ]
  }
 ]
}